# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'ca41e778-475a-42f0-9b0d-5a850157365e'
    command: 'buildAndPush'
    Dockerfile: '**/*.Dockerfile'
