# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- template: 'pipelines/capturecam.yml'
- template: 'pipelines/senshat.yml'
- template: 'pipelines/imageclassifier-base.yml'
- template: 'pipelines/imageclassifier-applebanana.yml'
- template: 'pipelines/imageclassifier-fruits.yml'
- template: 'pipelines/imageclassifier-fire.yml'
- template: 'pipelines/imageclassifier-door.yml'
- template: 'pipelines/imageclassifier-person.yml'










