# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  azureSubscription: '2.Microsoft Azure Sponsorship(54b31a7f-ee4b-4ea5-b3a3-7aae06defc8a)'
  azureContainerRegistry: '{"loginServer":"smartc.azurecr.io", "id" : "/subscriptions/54b31a7f-ee4b-4ea5-b3a3-7aae06defc8a/resourceGroups/CommonDemo/providers/Microsoft.ContainerRegistry/registries/smartc"}'

steps:
# Image Classifier Apples Bananas Model
- task: Docker@0
  displayName: 'Build an image'
  inputs:
    azureSubscription: $(azureSubscription)
    azureContainerRegistry: $(azureContainerRegistry)
    dockerFile: 'modules/ImageClassifierService/arm32v7-applesbananas.Dockerfile'
    imageName: 'imageclassifierservice-arm:$(Build.BuildId)'
    includeLatestTag: false

- task: Docker@0
  displayName: 'Push an image'
  inputs:
    azureSubscription: $(azureSubscription)
    azureContainerRegistry: $(azureContainerRegistry)
    action: 'Push an image'
    imageName: 'imageclassifierservice-arm:$(Build.BuildId)'
    includeLatestTag: false
    additionalImageTags: 'latest-applebanana'

# Image Classifier Fruits Model