# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  azureSubscription: '2.Microsoft Azure Sponsorship(54b31a7f-ee4b-4ea5-b3a3-7aae06defc8a)'
  azureContainerRegistry: '{"loginServer":"smartc.azurecr.io", "id" : "/subscriptions/54b31a7f-ee4b-4ea5-b3a3-7aae06defc8a/resourceGroups/CommonDemo/providers/Microsoft.ContainerRegistry/registries/smartc"}'
  imageclassifierARM: 'imageclassifierservice-arm'
  cameracaptureARM: 'cameracapture-arm'
  sensehatARM: 'sensehatdisplay'

steps:
# Capture Cam Module ARM
- task: Docker@0
  displayName: 'Build Capture Cam Module ARM'
  inputs:
    azureSubscription: $(azureSubscription)
    azureContainerRegistry: $(azureContainerRegistry)
    dockerFile: 'modules/CameraCapture/arm32v7.Dockerfile'
    imageName: '$(cameracaptureARM):$(Build.BuildId)'
    includeLatestTag: true

- task: Docker@0
  displayName: 'Push Capture Cam Module ARM'
  inputs:
    azureSubscription: $(azureSubscription)
    azureContainerRegistry: $(azureContainerRegistry)
    action: 'Push an image'
    imageName: '$(cameracaptureARM):$(Build.BuildId)'
    includeLatestTag: true

# Sense Hat Display ARM
- task: Docker@0
  displayName: 'Build Sense Hat Display ARM'
  inputs:
    azureSubscription: $(azureSubscription)
    azureContainerRegistry: $(azureContainerRegistry)
    dockerFile: 'modules/CameraCapture/arm32v7.Dockerfile'
    imageName: '$(sensehatARM):$(Build.BuildId)'
    includeLatestTag: true

- task: Docker@0
  displayName: 'Push Sense Hat Display ARM'
  inputs:
    azureSubscription: $(azureSubscription)
    azureContainerRegistry: $(azureContainerRegistry)
    action: 'Push an image'
    imageName: '$(sensehatARM):$(Build.BuildId)'
    includeLatestTag: true

# Image Classifier Apples Bananas Model ARM
- task: Docker@0
  displayName: 'Build Image Classifier Apples Bananas ARM'
  inputs:
    azureSubscription: $(azureSubscription)
    azureContainerRegistry: $(azureContainerRegistry)
    dockerFile: 'modules/ImageClassifierService/arm32v7-applesbananas.Dockerfile'
    imageName: '$(imageclassifierARM):$(Build.BuildId)'
    includeLatestTag: false
    additionalImageTags: 'latest-applebanana'

- task: Docker@0
  displayName: 'Push Image Classifier Apples Bananas ARM'
  inputs:
    azureSubscription: $(azureSubscription)
    azureContainerRegistry: $(azureContainerRegistry)
    action: 'Push an image'
    imageName: '$(imageclassifierARM):$(Build.BuildId)'
    includeLatestTag: false
    additionalImageTags: 'latest-applebanana'

# Image Classifier Fruits Model ARM
- task: Docker@0
  displayName: 'Build Image Classifier Fruits ARM'
  inputs:
    azureSubscription: $(azureSubscription)
    azureContainerRegistry: $(azureContainerRegistry)
    dockerFile: 'modules/ImageClassifierService/arm32v7-fruits.Dockerfile'
    imageName: '$(imageclassifierARM):$(Build.BuildId)'
    includeLatestTag: false
    additionalImageTags: 'latest-fruits'

- task: Docker@0
  displayName: 'Push Image Classifier Fruits ARM'
  inputs:
    azureSubscription: $(azureSubscription)
    azureContainerRegistry: $(azureContainerRegistry)
    action: 'Push an image'
    imageName: '$(imageclassifierARM):$(Build.BuildId)'
    includeLatestTag: false
    additionalImageTags: 'latest-fruits'

# Image Classifier Fire Model ARM
- task: Docker@0
  displayName: 'Build Image Classifier Fire ARM'
  inputs:
    azureSubscription: $(azureSubscription)
    azureContainerRegistry: $(azureContainerRegistry)
    dockerFile: 'modules/ImageClassifierService/arm32v7-fire.Dockerfile'
    imageName: '$(imageclassifierARM):$(Build.BuildId)'
    includeLatestTag: false
    additionalImageTags: 'latest-fire'

- task: Docker@0
  displayName: 'Push Image Classifier Fire ARM'
  inputs:
    azureSubscription: $(azureSubscription)
    azureContainerRegistry: $(azureContainerRegistry)
    action: 'Push an image'
    imageName: '$(imageclassifierARM):$(Build.BuildId)'
    includeLatestTag: false
    additionalImageTags: 'latest-fire'

# Image Classifier Door Model ARM
- task: Docker@0
  displayName: 'Build Image Classifier Door ARM'
  inputs:
    azureSubscription: $(azureSubscription)
    azureContainerRegistry: $(azureContainerRegistry)
    dockerFile: 'modules/ImageClassifierService/arm32v7-door.Dockerfile'
    imageName: '$(imageclassifierARM):$(Build.BuildId)'
    includeLatestTag: false
    additionalImageTags: 'latest-door'

- task: Docker@0
  displayName: 'Push Image Classifier Door ARM'
  inputs:
    azureSubscription: $(azureSubscription)
    azureContainerRegistry: $(azureContainerRegistry)
    action: 'Push an image'
    imageName: '$(imageclassifierARM):$(Build.BuildId)'
    includeLatestTag: false
    additionalImageTags: 'latest-door'

  # Image Classifier Person Model ARM
- task: Docker@0
  displayName: 'Build Image Classifier Person ARM'
  inputs:
    azureSubscription: $(azureSubscription)
    azureContainerRegistry: $(azureContainerRegistry)
    dockerFile: 'modules/ImageClassifierService/arm32v7-person.Dockerfile'
    imageName: '$(imageclassifierARM):$(Build.BuildId)'
    includeLatestTag: false
    additionalImageTags: 'latest-person'

- task: Docker@0
  displayName: 'Push Image Classifier Person ARM'
  inputs:
    azureSubscription: $(azureSubscription)
    azureContainerRegistry: $(azureContainerRegistry)
    action: 'Push an image'
    imageName: '$(imageclassifierARM):$(Build.BuildId)'
    includeLatestTag: false
    additionalImageTags: 'latest-person'