# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: 
- none

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  azureSubscription: '2.Microsoft Azure Sponsorship(54b31a7f-ee4b-4ea5-b3a3-7aae06defc8a)'
  azureContainerRegistry: '{"loginServer":"smartc.azurecr.io", "id" : "/subscriptions/54b31a7f-ee4b-4ea5-b3a3-7aae06defc8a/resourceGroups/CommonDemo/providers/Microsoft.ContainerRegistry/registries/smartc"}'
  imageclassifierbaseRegistry: 'smartc.azurecr.io'
  imageclassifierARM: 'imageclassifierservice-arm'
  cameracaptureARM: 'cameracapture-arm'
  sensehatARM: 'sensehatdisplay'
  edgedeploymentX64: 'edgedeployment-x64'
  webX64: 'web-x64'
  
steps:
- template: 'edgedeployment.yml'
- template: 'capturecam.yml'
- template: 'sensehat.yml'
- template: 'imageclassifier-base.yml'
- template: 'imageclassifier-applebanana.yml'
- template: 'imageclassifier-fruits.yml'
- template: 'imageclassifier-fire.yml'
- template: 'imageclassifier-door.yml'
- template: 'imageclassifier-fire_s1.yml'
- template: 'imageclassifier-door_s1.yml'
- template: 'imageclassifier-person.yml'
- template: 'web.yml'







