#Web Container Only
trigger: 
  branches:
    include:
    - master
  paths:
    include:
    - modelcontrol/web/*

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  azureSubscription: '2.Microsoft Azure Sponsorship(54b31a7f-ee4b-4ea5-b3a3-7aae06defc8a)'
  azureContainerRegistry: '{"loginServer":"smartc.azurecr.io", "id" : "/subscriptions/54b31a7f-ee4b-4ea5-b3a3-7aae06defc8a/resourceGroups/CommonDemo/providers/Microsoft.ContainerRegistry/registries/smartc"}'
  webX64: 'web-x64'

steps:
- template: 'web.yml'